<a href="https://colab.research.google.com/github/Risad-Raihan/ops_segmentation/blob/main/stock_calc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

In [4]:
df = pd.read_csv('/content/drive/My Drive/ops_segmentation-main/current_stock.csv')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16863 entries, 0 to 16862
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   intWarehouseId  16863 non-null  int64
 1   intItemId       16863 non-null  int64
 2   strItemName     16863 non-null  object
 3   strItemBarcode  16139 non-null  object
dtypes: int64(2), object(2)
memory usage: 527.1+ KB

In [7]:
# Assuming 'df' is your original DataFrame with the 'outlet' column intact

# Filter the DataFrame for rows where strItemBarcode is '0' or NULL
df_filtered = df[(df['strItemBarcode'].isnull()) | (df['strItemBarcode'] == '0')]

# Drop duplicates based on 'outlet' and 'Item_code' to get unique combinations
df_unique_filtered = df_filtered.drop_duplicates(subset=['intWarehouseId', 'intItemId'])

# Display the result
print(df_unique_filtered.info())
print(df_unique_filtered)

<class 'pandas.core.frame.DataFrame'>
Index: 2155 entries, 3 to 16860
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   intWarehouseId  2155 non-null   int64
 1   intItemId       2155 non-null   int64
 2   strItemName     2155 non-null   object
 3   strItemBarcode  1581 non-null   object
dtypes: int64(2), object(2)
memory usage: 84.2+ KB
None
       intWarehouseId  intItemId                    strItemName strItemBarcode
3               10252      55461        ACI Savlon Cream 100 gm              0
4               10255      55461        ACI Savlon Cream 100 gm              0
5               10258      55461        ACI Savlon Cream 100 gm              0
6               10243      55487  Veet Hair Removal Cream 25 gm              0
7               10268      55544       Meril Baby Powder 100 gm              0
...               ...        ...                            ...            ...
16856           10178      70570       Floor Hand Brush Plastic            NaN
16857           10178      70571    Kazi & Kazi Green Tea 60 Gm            NaN
16858           10222      70572              Mango Carat 1 Pcs            NaN
16859           10265      70572              Mango Carat 1 Pcs            NaN
16860           10257      70572              Mango Carat 1 Pcs            NaN

[2155 rows x 4 columns]

In [12]:
df_unique_filtered.head(5)

   outlet  intItemId                    strItemName strItemBarcode
3   10252      55461        ACI Savlon Cream 100 gm              0
4   10255      55461        ACI Savlon Cream 100 gm              0
5   10258      55461        ACI Savlon Cream 100 gm              0
6   10243      55487  Veet Hair Removal Cream 25 gm              0
7   10268      55544       Meril Baby Powder 100 gm              0

In [9]:
df2 = pd.read_csv('/content/drive/My Drive/ops_segmentation-main/outlets.csv')

In [10]:
df2.head(5)

   outlet                       outlet_name
0   10177         Picard Bangladesh Limited
1   10178           Green Smart Shirts Ltd.
2   10179  Apon Wellbeing Limited Corporate
3   10180               Alim Knit (BD) Ltd.
4   10181        Odyssey Crafts (Pvt.) Ltd.

In [11]:
df_unique_filtered.rename(columns={'intWarehouseId': 'outlet'}, inplace=True)

<ipython-input-11-542135c5887f>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unique_filtered.rename(columns={'intWarehouseId': 'outlet'}, inplace=True)

In [13]:
# Assuming df2 contains the columns 'outlet' and 'Outlet_name'

# Merge df_unique_filtered with df2 based on the 'outlet' column
df_result = pd.merge(df_unique_filtered, df2[['outlet', 'outlet_name']], on='outlet', how='left')

# Display the resulting DataFrame
print(df_result.info())
df_result.head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2155 entries, 0 to 2154
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   outlet          2155 non-null   int64
 1   intItemId       2155 non-null   int64
 2   strItemName     2155 non-null   object
 3   strItemBarcode  1581 non-null   object
 4   outlet_name     2154 non-null   object
dtypes: int64(2), object(3)
memory usage: 84.3+ KB
None

,outlet,intItemId,strItemName,strItemBarcode,outlet_name
0,10252,55461,ACI Savlon Cream 100 gm,0,Concorde Garments Ltd.
1,10255,55461,ACI Savlon Cream 100 gm,0,Interfab Shirt Manufacturing Limited Unit-02 (...
2,10258,55461,ACI Savlon Cream 100 gm,0,Abanti Colour Tex Limited
3,10243,55487,Veet Hair Removal Cream 25 gm,0,Continental Garments Ind. (Pvt.) Ltd.
4,10268,55544,Meril Baby Powder 100 gm,0,Evitex Dress Shirt Limited

In [ ]:
df_result.to_excel('df_result.xlsx')  # Default is index=True
print("Data exported to df_result.xlsx successfully!")

Data exported to df_result.xlsx successfully!

In [15]:
# Assume df_result is the DataFrame we previously created

# Sort df_result if necessary (optional, depending on how you want to pick the "first" instance)
# For example, sorting by 'outlet' to preferentially select from lower numbered outlets first
df_result_sorted = df_result.sort_values(by='outlet')

# Drop duplicates based on 'Item_code', keeping the first occurrence
df_final = df_result_sorted.drop_duplicates(subset='intItemId', keep='first')

# Display the final DataFrame to be sent to outlet managers
print(df_final.info())
df_final.head(5)

<class 'pandas.core.frame.DataFrame'>
Index: 580 entries, 432 to 90
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   outlet          580 non-null    int64
 1   intItemId       580 non-null    int64
 2   strItemName     580 non-null    object
 3   strItemBarcode  426 non-null    object
 4   outlet_name     579 non-null    object
dtypes: int64(2), object(3)
memory usage: 27.2+ KB
None

,outlet,intItemId,strItemName,strItemBarcode,outlet_name
432,10177,58124,Miniket Rice Premium,0,Picard Bangladesh Limited
659,10177,58305,Parachute Beliful Hair Oil 100 Gm,0,Picard Bangladesh Limited
649,10177,58291,Pangash Deshi 1 Kg,0,Picard Bangladesh Limited
1212,10177,69026,Mediplus Tooth Brush,0,Picard Bangladesh Limited
2052,10177,70404,Maya True Herbs Herbal Coconut Oil 200 ml,NaN,Picard Bangladesh Limited

In [19]:
df_final.to_excel('df_final.xlsx')  # Default is index=True
print("Data exported to df_final.xlsx successfully!")

Data exported to df_final.xlsx successfully!

In [17]:
# List of outlet names to exclude
excluded_outlets = [
    "Apon Wellbeing Limited Corporate",
    "Odyssey Crafts (Pvt.) Ltd.",
    "SQ Station",
    "Ananta Denim Technology Limited",
    "SQ Celsius Limited",
    "Ananta Casual Wear Ltd.",
    "Elite Garments Ltd"
]

# Filter df_result to exclude these outlet names
df_filtered = df_result[~df_result['outlet_name'].isin(excluded_outlets)]

# For each item_code in df_final that needs to be replaced, find an alternative
replacement_needed = df_final[df_final['outlet_name'].isin(excluded_outlets)]

# Find replacements
replacements = pd.DataFrame()

for index, row in replacement_needed.iterrows():
    alternative = df_filtered[(df_filtered['intItemId'] == row['intItemId']) & (df_filtered['strItemBarcode'].isin(['0', None]))].head(1)
    replacements = pd.concat([replacements, alternative], ignore_index=True)

# Drop the rows needing replacement from df_final
df_final = df_final[~df_final['intItemId'].isin(replacement_needed['intItemId'])]

# Concatenate the replacements into df_final
df_final = pd.concat([df_final, replacements], ignore_index=True)

# Removing any potential duplicates that might have been introduced
df_final = df_final.drop_duplicates(subset=['intItemId'], keep='first')

# Display the final DataFrame
print(df_final.info())
df_final.head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 523 entries, 0 to 522
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   outlet          523 non-null    int64
 1   intItemId       523 non-null    int64
 2   strItemName     523 non-null    object
 3   strItemBarcode  376 non-null    object
 4   outlet_name     522 non-null    object
dtypes: int64(2), object(3)
memory usage: 20.6+ KB
None

,outlet,intItemId,strItemName,strItemBarcode,outlet_name
0,10177,58124,Miniket Rice Premium,0,Picard Bangladesh Limited
1,10177,58305,Parachute Beliful Hair Oil 100 Gm,0,Picard Bangladesh Limited
2,10177,58291,Pangash Deshi 1 Kg,0,Picard Bangladesh Limited
3,10177,69026,Mediplus Tooth Brush,0,Picard Bangladesh Limited
4,10177,70404,Maya True Herbs Herbal Coconut Oil 200 ml,NaN,Picard Bangladesh Limited

In [18]:
df_final.to_excel('df_final3.xlsx')  # Default is index=True
print("Data exported to df_final2.xlsx successfully!")

Data exported to df_final2.xlsx successfully!

In [ ]:
df_unique.head(5)

   Item_code                    strItemName strItemBarcode
0      55382  DOVE Hair Fall Shampoo 170 ml  8941102467075
2      55461        ACI Savlon Cream 100 gm              0
5      55487  Veet Hair Removal Cream 25 gm              0
6      55596     Rose Water Glycerin 120 gm              0
7      55615       LUX Perfumed Soap 125 gm              0

In [ ]:
# DataFrame where strItemBarcode is '0' or NULL
df_barcode_null_or_zero = df_unique[(df_unique['strItemBarcode'].isnull()) | (df_unique['strItemBarcode'] == '0')]

# DataFrame where strItemBarcode is anything other than '0' or NULL
df_barcode_non_zero = df_unique[(df_unique['strItemBarcode'].notnull()) & (df_unique['strItemBarcode'] != '0')]

# Display the info of both DataFrames
print("DataFrame with strItemBarcode as '0' or NULL:")
print(df_barcode_null_or_zero.info())

print("\nDataFrame with strItemBarcode as non-zero and not NULL:")
print(df_barcode_non_zero.info())

DataFrame with strItemBarcode as '0' or NULL:
<class 'pandas.core.frame.DataFrame'>
Index: 694 entries, 2 to 17400
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Item_code       694 non-null    int64
 1   strItemName     694 non-null    object
 2   strItemBarcode  504 non-null    object
dtypes: int64(1), object(2)
memory usage: 21.7+ KB
None

DataFrame with strItemBarcode as non-zero and not NULL:
<class 'pandas.core.frame.DataFrame'>
Index: 687 entries, 0 to 17377
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Item_code       687 non-null    int64
 1   strItemName     687 non-null    object
 2   strItemBarcode  687 non-null    object
dtypes: int64(1), object(2)
memory usage: 21.5+ KB
None

In [ ]:
df_barcode_null_or_zero.head(5)

    Item_code                    strItemName strItemBarcode
2       55461        ACI Savlon Cream 100 gm              0
5       55487  Veet Hair Removal Cream 25 gm              0
6       55596     Rose Water Glycerin 120 gm              0
7       55615       LUX Perfumed Soap 125 gm              0
14      55689        Ifad Chesse Bite 300 gm              0

In [ ]:
df_barcode_non_zero.head(5)

    Item_code                       strItemName strItemBarcode
0       55382     DOVE Hair Fall Shampoo 170 ml  8941102467075
8       55688      Ifad Stick Jhal Toast 350 gm  8941168013087
34      56339        Vim Dishwash Liquid 250 ml  8941100618073
45      57299                ACI Aerosol 475 Ml   813903000035
65      57301  Aci Angelic Air Freshener 300 Ml  8139003000846

In [ ]:
df_barcode_null_or_zero.to_excel('df_barcode_null_or_zero.xlsx')  # Default is index=True
print("Data exported to df_barcode_null_or_zero.xlsx successfully!")

Data exported to df_barcode_null_or_zero.xlsx successfully!

In [ ]:
df_barcode_non_zero.to_excel('df_barcode_non_zero.xlsx')  # Default is index=True
print("Data exported to df_barcode_non_zero.xlsx successfully!")

Data exported to df_barcode_non_zero.xlsx successfully!

In [ ]:
# Filter the DataFrame for rows where strItemBarcode is '0' or NULL
df_filtered = df[(df['strItemBarcode'].isnull()) | (df['strItemBarcode'] == '0')]

# Drop duplicates based on 'outlet' and 'Item_code' to get unique combinations
df_unique_filtered = df_filtered.drop_duplicates(subset=['outlet', 'Item_code'])

# Display the result
print(df_unique_filtered.info())
print(df_unique_filtered)

KeyError: Index(['outlet'], dtype='object')